package com.kandong.modelprobe

/** Frozen semantic expectations, never passed into the guard or adapter. */
internal object ConditionGuardExpectations {
    data class Expected(val complete:List<Set<String>>,val protected:Set<String>,val hold:Boolean)
    val pages=mapOf(
        "en-shifted-before" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "en-bottom-positive" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "fr-accent-after" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "fr-right-column-before" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "en-two-columns" to Expected(listOf(setOf("left-head","left-tail"),setOf("right-head","right-tail")),setOf("left-head","left-tail","right-head","right-tail"),false),
        "fr-seam-exact-duplicate" to Expected(listOf(setOf("a-head","b-head","a-tail","b-tail")),setOf("a-head","a-tail","b-head","b-tail"),false),
        "en-seam-drift-duplicate" to Expected(listOf(setOf("a-head","b-head","a-tail","b-tail")),setOf("a-head","a-tail","b-head","b-tail"),false),
        "fr-seam-polarity-conflict" to Expected(listOf(),setOf("a-head","a-tail","b-head","b-tail"),false),
        "en-duplicate-tail" to Expected(listOf(setOf("head","tail","tail-copy")),setOf("head","tail","tail-copy"),false),
        "en-same-strip-copy" to Expected(listOf(),setOf("head","tail","head-copy"),false),
        "fr-repeated-different-rows" to Expected(listOf(setOf("first-head","first-tail"),setOf("second-head","second-tail")),setOf("first-head","first-tail","second-head","second-tail"),false),
        "en-cross-column-fragment" to Expected(listOf(),setOf("head","tail"),false),
        "fr-intervening-label" to Expected(listOf(),setOf("head","tail"),false),
        "en-spaced-complete" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "fr-indented-complete" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "en-trailing-exception" to Expected(listOf(setOf("head","tail","exception")),setOf("head","tail","exception"),true),
        "fr-trailing-restriction" to Expected(listOf(setOf("head","tail","restriction")),setOf("head","tail","restriction"),true),
        "en-leading-negated-claim" to Expected(listOf(setOf("negated-claim","head","tail")),setOf("negated-claim","head","tail"),true),
        "fr-leading-prerequisite" to Expected(listOf(setOf("prerequisite","head","tail")),setOf("prerequisite","head","tail"),true),
        "en-neutral-neighbour" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "fr-independent-neighbour" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "en-clipped-head-conflict" to Expected(listOf(),setOf("head-clipped","head-full","tail"),false),
        "hans-source-only" to Expected(listOf(),setOf(),false),
        "hant-source-only" to Expected(listOf(),setOf(),false),
        "en-unless-before" to Expected(listOf(setOf("head","tail","modifier0")),setOf("head","tail","modifier0"),true),
        "en-provided-distant" to Expected(listOf(setOf("head","tail","modifier0")),setOf("head","tail","modifier0"),true),
        "en-only-nbsp" to Expected(listOf(setOf("head","tail","modifier0")),setOf("head","tail","modifier0"),true),
        "en-except-split" to Expected(listOf(setOf("head","tail","modifier0","modifier1")),setOf("head","tail","modifier0","modifier1"),true),
        "en-negated-heading" to Expected(listOf(setOf("head","tail","modifier0")),setOf("head","tail","modifier0"),true),
        "en-required-column" to Expected(listOf(setOf("head","tail","modifier0")),setOf("head","tail","modifier0"),true),
        "fr-sauf-before" to Expected(listOf(setOf("head","tail","modifier0")),setOf("head","tail","modifier0"),true),
        "fr-reserve-distant" to Expected(listOf(setOf("head","tail","modifier0")),setOf("head","tail","modifier0"),true),
        "fr-condition-split" to Expected(listOf(setOf("head","tail","modifier0","modifier1")),setOf("head","tail","modifier0","modifier1"),true),
        "fr-negative-heading" to Expected(listOf(setOf("head","tail","modifier0")),setOf("head","tail","modifier0"),true),
        "fr-sans-column" to Expected(listOf(setOf("head","tail","modifier0")),setOf("head","tail","modifier0"),true),
        "fr-uniquement-after" to Expected(listOf(setOf("head","tail","modifier0")),setOf("head","tail","modifier0"),true),
        "en-plain" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "fr-plain" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "en-plain-neighbour" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "fr-plain-neighbour" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),false),
        "en-independent-if" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),true),
        "fr-independent-si" to Expected(listOf(setOf("head","tail")),setOf("head","tail"),true),
    )
}
